### PR TITLE
Added extraction functionality

### PR DESCRIPTION
**Pull request by bbuzzanga**
Added method GetNames to Swmm_Extract Class
	get the names of subcatchments or nodes.

Added function GetDates
	returns tuple of start/end date

Added function extract_arr
	same as extract except returns a numpy array instead of panda series

(Started using git today - first pull request, sorry if it's a mess!)

### CODE REVIEW

**Comment by timcera** [comment]
Thank you!

getnames:
I have a test called "tstoolbox.tsutils.test_cli()" that figures out whether the command was called at the command line or as a function.  Using that test you can print to the screen when using the command line interface and returning an object if within Python.  Look at the "listdsns" function in https://github.com/timcera/wdmtoolbox/blob/master/wdmtoolbox/wdmtoolbox.py to see how it is used.  If you use "tstoolbox.tsutils.test_cli()" I think you can get the same functionality by adding what you are doing in "getnames" to "listdetail".

GetDates:
This could be a good command to have at the command line also.  Would have to use "tsttoolbox.tsutils.test_cli()" to do different things depending on the calling context.

extract_arr:
Once you get used to Pandas DataFrames you can too easily make numpy arrays.  Basically, it is "numpy_arr = dataframe.values" or do you want something different that I am missing?  I wouldn't mind keeping 'extract_arr' but it should just call 'extract' and just return the values of the DataFrame.

So, how involved do you want to be?  Do you want to make the changes mentioned above?  I don't mind either way.  You PR is fine in terms of git.  If you stay in the same branch in your working copy and push commits to your github fork, then those commits get added to the PR.

I could probably make "tstoolbox.tsutils.printiso()" more powerful.  Right now if called from the command line it prints the DataFrame to stdout and if called from within a Python script returns the DataFrame.  Should have the option of printing/returning other objects like lists and dictionaries.  Then you could just call 'listdetail' from within Python and get a list returned.

Kindest regards,
Tim

**Comment by timcera** [comment]
How did you do that so fast?

This is great!  

Does it do everything that you need?  Do you have other changes you want to make?

**Comment by bbuzzanga** [comment]
Welcome Tim.
You're right about the listdetail / get names.
I added some simple cli checks with your function before the print statements and returned the list of itemttype names.

I left the GetDates - in answer to your 'how involved would you like to be' I really should be actually writing my thesis instead of playing with GitHub haha.

The extract_arr function is useful for two reasons.
One, I'm extracting a year TS from a thousand+ subcatchments, so pulling from numpy directly saves some overhead in creating the pandas series.
Two, having the np results is a bit more flexible, in case you want to use different containers or column names and such.

So yup, it does everything I need!
This toolkit has been probably saved me a month or so of learning how to parse a binary file (I'm still relatively new to programming).
Thanks so much!

**Comment by bbuzzanga** [comment]
Also I suppose you answered this with your comment but just checking:
If I make a pull request, and then commit changes to it before it's accepted, they are automatically updated -- I don't have to submit a new pull request?

**Comment by timcera** [comment]
You do not have to submit a new pull request.

Thank you again.  I merged this pull request.  I have stuff to do to make the tests work again, reformatting,...etc. so it may take some time to see this in a released version.

I am glad that swmmtoolbox was useful to you.

Kindest regards,
Tim

**Pull request merged**
